@host=http://localhost:3000

### 회원가입
POST {{host}}/api/users
Content-Type: application/json

{
  "email" : "test@example.com",
  "name" : "test",
  "password" : "1234"
}

### 내 정보 조회
get {{host}}/api/users
Content-Type: application/json